### ISSUE TITLE
UI bug

### ISSUE THREAD

**Issue by netroby** [jpillora/cloud-torrent#14]
While try to add magnet link to download torrent,show error: ui bug
```
Error: [$rootScope:inprog] http://errors.angularjs.org/1.3.15/$rootScope/inprog?p0=%24apply
    at Error (native)
    at http://test.demo.com:9232/js/vendor/angular.min.js:7:417
    at p (http://test.demo.com:9232/js/vendor/angular.min.js:119:370)
    at n.$apply (http://test.demo.com:9232/js/vendor/angular.min.js:127:224)
    at HTMLInputElement.<anonymous> (http://test.demo.com:9232/js/utils.js:101:15)
    at HTMLInputElement.c (http://test.demo.com:9232/js/vendor/angular.min.js:33:389)
    at n.$scope.submitTorrent (http://test.demo.com:9232/js/omni-controller.js:139:14)
    at n.$scope.submitOmni (http://test.demo.com:9232/js/omni-controller.js:129:14)
    at http://test.demo.com:9232/js/vendor/angular.min.js:200:303
    at n.$eval (http://test.demo.com:9232/js/vendor/angular.min.js:127:15)
```

**Comment by jpillora** [comment]
thanks, will look into it

**Comment by jpillora** [comment]
Couldn't reproduce, maybe it got fixed at some point, reopen if needed
