### ISSUE TITLE
Crash when download some torrent file

### ISSUE THREAD

**Issue by zhouzhenqi** [jpillora/cloud-torrent#208]
goroutine 4760 [running]:
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.(*Peer).fromDictInterface(0xc4209d59a8, 0xc423f17530)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/peer.go:8 +0x217
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.(*httpResponse).UnmarshalPeers(0xc4243384c0, 0x34, 0x200, 0x92eba0, 0xc4243384c0, 0x0)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/http.go:46 +0x12f
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.announceHTTP(0xc42047cd20, 0xc420695100, 0xc4209ca187, 0x16, 0x5460, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/http.go:105 +0x6c8
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.AnnounceHost(0xc42046c520, 0x20, 0xc42047cd20, 0xc4209ca187, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/tracker.go:67 +0x149
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*trackerScraper).announce(0xc4209b0cc0, 0x0, 0x0, 0x0, 0x45d964b800, 0xbe7743519fdb0c52, 0xb458d90c9, 0xdc7a40)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker_scraper.go:88 +0x299
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*trackerScraper).Run(0xc4209b0cc0)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker_scraper.go:109 +0x208
created by github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*Torrent).startScrapingTracker
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/torrent.go:1197 +0x13f

**Comment by WingGao** [comment]
panic: interface conversion: interface {} is nil, not string

goroutine 2442 [running]:
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.(*Peer).fromDictInterface(0xc4205979a8, 0xc4208a48d0)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/peer.go:8 +0x217
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.(*httpResponse).UnmarshalPeers(0xc420997980, 0x34, 0x200, 0x92eba0, 0xc420997980, 0x0)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/http.go:46 +0x12f
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.announceHTTP(0xc42025bb00, 0xc4201cf480, 0xc4202dd9b7, 0x16, 0x5460, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/http.go:105 +0x6c8
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.AnnounceHost(0xc420327840, 0x20, 0xc42025bb00, 0xc4202dd9b7, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/tracker.go:67 +0x149
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*trackerScraper).announce(0xc420144600, 0x0, 0x0, 0x0, 0x45d964b800, 0xbe793981ac9537d3, 0x2141175cb, 0xdc7a40)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker_scraper.go:88 +0x299
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*trackerScraper).Run(0xc420144600)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker_scraper.go:109 +0x208
created by github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*Torrent).startScrapingTracker
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/torrent.go:1197 +0x13f

**Comment by BruceWangNo1** [comment]
Please specify one torrent file which causes this problem if you can.
