### ISSUE TITLE
It's crashed when i add torrent.

### ISSUE THREAD

**Issue by feilongfl** [jpillora/cloud-torrent#217]
## error torrent
> https://mikanani.me/Download/20180209/004e8c01ad2149059ed7c2ebe604796973d81d26.torrent
## my vps system overview:
```
root@feilong ~/ct# uname -a
Linux feilong 2.6.32-042stab127.2 #1 SMP Thu Jan 4 16:41:44 MSK 2018 x86_64 GNU/Linux
```
## cloud torrent argvs
> ./cloud-torrent_linux_amd64 -p 443 -k /key.key -r /certificate.pem -a pass:pass  

## error msg
```
panic: interface conversion: interface {} is nil, not string

goroutine 4513 [running]:
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.(*Peer).fromDictInterface(0xc42417b9a8, 0xc423fb2ab0)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/peer.go:8 +0x217
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.(*httpResponse).UnmarshalPeers(0xc4221b9c80, 0x34, 0x200, 0x92eba0, 0xc4221b9c80, 0x0)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/http.go:46 +0x12f
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.announceHTTP(0xc4209bae40, 0xc420496b00, 0xc4202b6a57, 0x16, 0x5460, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/http.go:105 +0x6c8
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker.AnnounceHost(0xc420331cc0, 0x20, 0xc4209bae40, 0xc4202b6a57, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker/tracker.go:67 +0x149
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*trackerScraper).announce(0xc42003f140, 0x0, 0x0, 0x0, 0x45d964b800, 0xbe97638b956d4169, 0x528a9c4d2, 0xdc7a40)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker_scraper.go:88 +0x299
github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*trackerScraper).Run(0xc42003f140)
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/tracker_scraper.go:109 +0x208
created by github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent.(*Torrent).startScrapingTracker
        /app/src/github.com/jpillora/cloud-torrent/vendor/github.com/anacrolix/torrent/torrent.go:1197 +0x13f

```

**Comment by steakunderscore** [comment]
I was unable to reproduce this both on master and using the docker image. @feilongfl is this still an issue?
